{% set name = "napari-mzarr" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-mzarr-{{ version }}.tar.gz
  sha256: 48ad64e131c1abb3833d7662e016d3e5631e3d355406410614552c73d18e150e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dask-core
    - imagecodecs ==2023.1.23
    - numcodecs
    - numpy
    - napari
    - python >={{ python_min }}
    - zarr

test:
  imports:
    - napari_mzarr
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-mzarr
  summary: A reader and writer plugin for the Mzarr image format.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
